version: '3.6'
services:
  mysql:
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=translation
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    container_name: mysqldb
    image: mysql
